### ISSUE TITLE
Possible inflection errors

### ISSUE THREAD

**Issue by ryskina** [apertium/apertium-tyv#2]
I've been comparing Apertium-generated paradigms with the ones in Iskhakov & Pal'mbakh 1961 grammar book (Ф. Г. Исхаков, А. А. Пальмбах. Грамматика тувинского языка: Фонетика и морфология.) and found some mismatches. 
**Disclaimer:** I am not a speaker of Tuvan.

1. Some Apertium-generated imperative forms for ``кел``:
   ```
   келеалыңар:кел<v><iv><imp><p1><pl>
   келейн:кел<v><iv><imp><p1><sg>
   келеалы:кел<v><iv><imp><p1><du>
   ```
   I&P book has ``келиилиңер, келийн, келиили`` respectively (pp. 391-392).

2. Some ``<p3><pl>`` forms have a double ``-лер``. I haven't seen this in the literature and it looked suspicious.
   ```
   келдилер:кел<v><iv><ifi><p3><pl>
   келдилерлер:кел<v><iv><ifi><p3><pl>
   ```
   I&P has ``келдилер`` for this analysis (I&P 365), and [Harrison, 2000](https://www.swarthmore.edu/SocSci/dharris2/Harrison-Dissertation.pdf) has ``keldi(ler)``. The same pattern in other tenses:
   ```
   келгеннер:кел<v><iv><ger_past><nom>+э<cop><aor><p3><pl>
   келгеннерлер:кел<v><iv><ger_past><nom>+э<cop><aor><p3><pl>
   келгендирлер:кел<v><iv><ger_past><nom>+э<cop><aor><evid><p3><pl>
   келгендирлерлер:кел<v><iv><ger_past><nom>+э<cop><aor><evid><p3><pl>
   ...
   ```

**Comment by ryskina** [comment]
Update on 1: the analyzer inflects ``номчу`` and ``ал`` incorrectly:

```
номчуайн/номчу<v><tv><imp><p1><sg>
алайн/ал<v><tv><imp><p1><sg>
```
I&P have ``номчууйн``and ``алыйн``.

**Comment by jonorthwash** [comment]
> келеалыңар:кел<v><iv><imp><p1><pl>

Is this supposed to be `<p1>` or `<p2>`?

**Comment by jonorthwash** [comment]
> 2\. Some `<p3><pl>` forms have a double `-лер`. I haven't seen this in the literature and it looked suspicious.
>     ```
>     келдилер:кел<v><iv><ifi><p3><pl>
>     келдилерлер:кел<v><iv><ifi><p3><pl>
>     ```

This is an alternative form in the transducer, available for analysis only.  If you don't want to see it, you should use the generator, not the analyser.

**Comment by ryskina** [comment]
Thanks! I've generated the forms using 
```
echo "[ к е л  %<v%> [ ? - [ %+ | %<subst%> ] ]* ]" | hfst-regexp2fst -o prefix.hfst
hfst-invert .deps/tyv.LR.hfst | hfst-compose-intersect -1 - -2 prefix.hfst | hfst-fst2strings 
```
Is there a different way I should use that would exclude analysis-only forms?

**Comment by ftyers** [comment]
You can try using `.deps/tyv.RL.hfst` if it exists.

**Comment by ryskina** [comment]
Sorry, do you mean using it without the ``hfst-invert``?

**Comment by jonorthwash** [comment]
I think @ftyers means to use the `RL` file instead of the `LR` file with `hfst-invert`, yes.  The `RL` file has all the analyses removed that we would normally want to analyse and not generate, and constitutes a stage in the creation of the generator.

**Comment by ryskina** [comment]
Thank you! Sorry, I misread @ftyers's comment. The forms are correct now, and changing from ``LR`` to ``RL`` was helpful!
